# SPDX-FileCopyrightText: 2026 James Rich
# SPDX-License-Identifier: GPL-3.0-only
#
# Shared helpers, prepended to sync.sh and worktree.sh by the flake's
# writeShellApplication (there is no shebang or `source` here — the flake
# concatenates the files, so ShellCheck still sees each tool whole).
#
# The flake exports the values Nix must supply, via runtimeEnv:
#   NIXTASTIC_REPOS_TSV   the workspace table: <dir>\t<org/repo>\t<shell>
#   NIXTASTIC_UV          store path of uv           (write_mcp_json)
#   NIXTASTIC_PY          store path of python3      (must match .#mcp)
#   NIXTASTIC_LIB         loader path for manylinux wheels (see AGENTS.md)
#
# write_mcp_json — the meshtastic-mcp registration, generated for the same
# reason the .envrc files are: machine-specific, yet it must survive a
# fresh machine. `claude mcp add` would land it in ~/.claude.json, outside
# the workspace, where sync cannot rebuild it and every worktree silently
# loses the tools. uv and the interpreter are STORE PATHS, not PATH
# lookups: the MCP client launches this without direnv. They go stale on
# `nix flake update`; re-run .#sync. Wrapping the command in `nix develop`
# instead was measured at 4.6s per server start. LD_LIBRARY_PATH restates
# the .#mcp shellHook because the server runs outside that shell.
# A TRACKED .mcp.json always wins over ours — see the callers.
#
# $1 = directory to write into, $2 = workspace root.
# shellcheck disable=SC2016
write_mcp_json() {
  [ -d "$2/meshtastic-mcp" ] || return 1
  jq -n \
    --arg root "$2" \
    --arg uv "$NIXTASTIC_UV" \
    --arg py "$NIXTASTIC_PY" \
    --arg lib "$NIXTASTIC_LIB" \
    --arg sdk "${ANDROID_HOME:-$HOME/Android/Sdk}" \
    '{
      "//": "Generated by: nix run .#sync — regenerate, do not hand-edit.",
      mcpServers: {
        meshtastic: {
          type: "stdio",
          command: $uv,
          args: [ "run", "--directory", ($root + "/meshtastic-mcp"), "meshtastic-mcp" ],
          env: {
            MESHTASTIC_WORKSPACE: $root,
            MESHTASTIC_FIRMWARE_ROOT: ($root + "/firmware"),
            MESHTASTIC_ANDROID_ROOT: ($root + "/android"),
            MESHTASTIC_APPLE_ROOT: ($root + "/apple"),
            MESHTASTIC_MCP_SDK_CLI: ($root + "/meshtastic-sdk/samples/cli/build/install/cli/bin/cli"),
            ANDROID_HOME: $sdk,
            UV_PYTHON: $py,
            UV_PYTHON_DOWNLOADS: "never",
            LD_LIBRARY_PATH: $lib
          }
        }
      }
    }' > "$1/.mcp.json"
}
# The user-scope answer to the one place project scope cannot reach:
# android, firmware and meshtastic-mcp TRACK their own .mcp.json, so ours
# is never written there and the meshtastic tools are absent in those
# repos and their worktrees. A USER-scope registration applies to every
# directory on the machine — its historical objection (store paths going
# stale outside sync's reach) dissolves by registering this STABLE PATH
# instead: sync rewrites the launcher's contents with fresh store paths
# every run, while the path itself never changes. Register once:
#   claude mcp add --scope user meshtastic -- <root>/bin/meshtastic-mcp-launch
# Project scope still wins where a project .mcp.json defines the same
# server name, so the root registration behaves exactly as before.
#
# $1 = workspace root.
# shellcheck disable=SC2016
write_mcp_launcher() {
  [ -d "$1/meshtastic-mcp" ] || return 1
  mkdir -p "$1/bin"
  {
    echo '#!/usr/bin/env bash'
    echo '# Generated by: nix run .#sync — regenerate, do not hand-edit.'
    echo '# A stable path over moving store paths. Register it USER-scope once:'
    printf '#   claude mcp add --scope user meshtastic -- %s/bin/meshtastic-mcp-launch\n' "$1"
    echo '# and the meshtastic tools reach every directory on this machine,'
    echo '# including the repos whose upstream-tracked .mcp.json cannot carry ours.'
    printf 'export MESHTASTIC_WORKSPACE="%s"\n' "$1"
    printf 'export MESHTASTIC_FIRMWARE_ROOT="%s/firmware"\n' "$1"
    printf 'export MESHTASTIC_ANDROID_ROOT="%s/android"\n' "$1"
    printf 'export MESHTASTIC_APPLE_ROOT="%s/apple"\n' "$1"
    printf 'export MESHTASTIC_MCP_SDK_CLI="%s/meshtastic-sdk/samples/cli/build/install/cli/bin/cli"\n' "$1"
    printf 'export ANDROID_HOME="%s"\n' "${ANDROID_HOME:-$HOME/Android/Sdk}"
    printf 'export UV_PYTHON="%s"\n' "$NIXTASTIC_PY"
    echo 'export UV_PYTHON_DOWNLOADS=never'
    printf 'export LD_LIBRARY_PATH="%s"\n' "$NIXTASTIC_LIB"
    printf 'exec "%s" run --directory "%s/meshtastic-mcp" meshtastic-mcp "$@"\n' "$NIXTASTIC_UV" "$1"
  } > "$1/bin/meshtastic-mcp-launch"
  chmod +x "$1/bin/meshtastic-mcp-launch"
}

# Ignore the generated files via .git/info/exclude (local, never
# committed): editing a tracked .gitignore in someone else's repo is not
# ours to do. --path-format=absolute is load-bearing — `rev-parse -C <p>
# --git-common-dir` answers RELATIVE to <p> (".git"), and using that from
# the caller's cwd once put every pattern in the WORKSPACE repo's exclude
# file instead (see 7388ecb).
#
# $1 = path to a repo's main checkout.
ensure_excludes() {
  ex="$(git -C "$1" rev-parse --path-format=absolute --git-common-dir)/info/exclude"
  for pat in '.claude/worktrees/' '.envrc' '.envrc-workspace' '.direnv/' '.mcp.json'; do
    grep -qxF "$pat" "$ex" 2>/dev/null || echo "$pat" >> "$ex"
  done
}
# $1 = file to write ( .envrc or .envrc-workspace ), $2 = shell.
# Uses $root from the caller.
write_worktree_envrc() {
  {
    echo '# Generated by: nix run .#sync / .#worktree — regenerate, do not hand-edit.'
    echo '# Selects the repo shell explicitly. The root is hardcoded because a'
    echo '# worktree can sit anywhere; deriving it from the cwd cannot work here.'
    printf 'export MESHTASTIC_WORKSPACE="%s"\n' "$root"
    printf 'use flake "%s#%s"\n' "$root" "$2"
  } > "$1"
}

# Per-repo subagents are invisible to a session rooted at the workspace:
# Claude Code scans `.claude/agents/` from the cwd up to the enclosing repo
# root, and the org repos are not ancestors of the workspace root. So
# `brief` would list android's gradle-runner while the Agent tool rejected
# it — advertised and unusable, which is how a bad build report reached the
# main context on 2026-08-01.
#
# Copies rather than symlinks. Skills document symlink support; subagents
# do NOT, and an agent that silently fails to load is precisely the class
# of failure this workspace refuses to ship. Byte-identical copies also put
# staleness one `cmp` away, which is how doctor checks them.
#
# The Agent tool resolves the frontmatter `name:`, never the filename, so
# the copies keep upstream's name verbatim — android's own CLAUDE.md says
# "dispatch the `gradle-runner` subagent" and that has to keep working from
# here. The repo prefix on the filename is for humans reading the directory
# and to keep two repos' files from overwriting each other.
#
# $1 = repo dir name, $2 = workspace root. Emits "<src>\t<destfilename>".
agent_pairs() {
  [ -d "$2/$1/.claude/agents" ] || return 0
  for f in "$2/$1/.claude/agents"/*.md; do
    [ -f "$f" ] || continue
    printf '%s\t%s--%s\n' "$f" "$1" "${f##*/}"
  done
}

# The name the Agent tool will actually resolve this file by.
agent_name_of() { sed -n 's/^name:[[:space:]]*//p' "$1" | head -1; }

# Per-repo SKILLS cannot be aggregated the way subagents are: a skill is a
# directory, and its identity is that directory's name, so copying them to
# the root would fork 14 living directories against their upstreams. The
# only supported way to load them from elsewhere is `--add-dir`, which has
# no settings.json equivalent — it must be passed at launch. This writes the
# launcher that does it, at a stable path, regenerated every sync so a repo
# added to the table is picked up.
#
# Repos are NAMED, never all-added by default, and that is the whole design:
# --add-dir also loads that directory's CLAUDE.md, and this workspace's root
# CLAUDE.md is a deliberately small router precisely because the per-repo
# agent docs are too large to all be loaded. `claude-ws android` pays for
# android and nothing else — the same "load only what this task needs" rule
# brief exists to enforce.
#
# $1 = workspace root. Uses $NIXTASTIC_REPOS_TSV.
#
# SC2016 is disabled for the whole function on purpose, exactly as for
# write_envrc: the $ must reach the generated file literally, to be expanded
# later by that script's own shell, not now by us.
# shellcheck disable=SC2016
write_claude_launcher() {
  mkdir -p "$1/bin"
  alts=$(while IFS=$'\t' read -r d _ _; do printf '%s|' "$d"; done < "$NIXTASTIC_REPOS_TSV")
  {
    echo '#!/bin/sh'
    echo '# Generated by: nix run .#sync — regenerate, do not hand-edit.'
    echo '#'
    echo '# usage: claude-ws [repo ...] [claude args ...]'
    echo '#'
    echo '# Leading arguments that name a workspace repo become --add-dir, which'
    echo '# is what makes that repo Claude Code SKILLS (and its CLAUDE.md, and'
    echo '# its file tree) reachable from a workspace-root session. Everything'
    echo '# from the first non-repo argument onward is passed to claude'
    echo '# untouched. With no repo named this is exactly plain claude.'
    printf 'root="%s"\n' "$1"
    echo 'add=""'
    echo 'while [ $# -gt 0 ]; do'
    printf '  case "$1" in\n'
    printf '    %s) add="$add --add-dir $root/$1"; shift ;;\n' "${alts%|}"
    printf '    *) break ;;\n'
    printf '  esac\n'
    echo 'done'
    echo '# Unquoted on purpose: $add is a list of flags, not one argument.'
    echo '# shellcheck disable=SC2086'
    echo 'exec claude $add "$@"'
  } > "$1/bin/claude-ws"
  chmod +x "$1/bin/claude-ws"
}
