# SPDX-FileCopyrightText: 2026 James Rich
# SPDX-License-Identifier: GPL-3.0-only
#
# nix run .#sync — clone missing repos, report drift, regenerate the
# machine-specific files, adopt stray worktrees. Assembled by the flake:
# lib.sh is prepended and the NIXTASTIC_* env vars are exported there.

# Modes:
#   (default)  clone anything missing, fetch, report status.
#              Never modifies a working tree.
#   --pull     additionally FAST-FORWARD branches that can be
#              fast-forwarded. Never merges, never rebases,
#              never touches a dirty or diverged repo.
#
# The conservatism is deliberate: these repos routinely sit on
# feature branches with work in progress, and a blanket
# `git pull` would either create merge commits or fail dirty.
#   --main     switch each repo to its DEFAULT branch first,
#              then pull. Implies --pull. Refuses to switch a
#              repo whose tracked files are modified.
#   --install-hooks  (retired) the hooks ship in the plugin; prints a pointer
#   --memory-only    the memory pass alone — after worktree churn, or when
#                    doctor says unpushed; everything else is a 19-repo fetch
#   --slug <path>    print a Claude Code project slug and exit
# --slug <path>: print the Claude Code project slug for a path and exit.
# Not a mode — a lookup, for humans asking "which projects/ dir is mine?"
if [ "${1:-}" = --slug ]; then
  slug_of "${2:?usage: --slug <absolute path>}"
  exit
fi
pull=false
main=false
hooks=false
memory_only=false
for arg in "$@"; do
  case "$arg" in
    --pull) pull=true ;;
    --main) main=true; pull=true ;;
    --install-hooks) hooks=true ;;
    --memory-only) memory_only=true ;;
    *) echo "unknown option: $arg" ; exit 1 ;;
  esac
done

root="${MESHTASTIC_WORKSPACE:-$PWD}"
if [ "$main" = true ]; then mode="  (--main)"
elif [ "$pull" = true ]; then mode="  (--pull)"
else mode=""; fi
echo "workspace: $root$mode"
echo ""

# Per-repo direnv activation. Without a .envrc in the repo
# itself, `cd android` loads the workspace-ROOT .envrc and you
# silently get the DEFAULT shell — wrong toolchain, no error.
#
# MESHTASTIC_WORKSPACE is exported BEFORE `use flake` because
# nix-direnv runs the flake's shellHook during use_flake, and
# that hook pins the JDKs and GRADLE_USER_HOME only when the
# variable is already set. Exporting it after would leave the
# pinning inert — the failure mode AGENTS.md documents.
#
# The path is derived, never hardcoded: repos are always direct
# children of the workspace, and the workspace is relocatable.
# SC2016 is disabled for the whole function on purpose: the $ and
# the command substitution must reach the generated file
# literally, to be expanded later by direnv, not now by us.
# shellcheck disable=SC2016
write_envrc() {
  cat > "$1" <<'EOF'
# Generated by: nix run .#sync   (untracked; do not commit)
# Selects the dev shell for this repo.
#
# The export must come BEFORE use flake. nix-direnv runs the
# flake shellHook during use_flake, and that hook pins the JDKs
# and GRADLE_USER_HOME only if MESHTASTIC_WORKSPACE is set.
#
# The path is derived, not hardcoded: repos are always direct
# children of the workspace, and the workspace is relocatable.
export MESHTASTIC_WORKSPACE="$(dirname "$PWD")"
EOF
  printf 'use flake "$MESHTASTIC_WORKSPACE#%s"\n' "$2" >> "$1"
}

# --- memory: one store, every slug a symlink into it -------------------
# Design and measurements: notes/agent-memory-sync.md. The order is pull →
# link/import → render → commit → push, so a run on either machine both
# takes the other's memories and hands over its own. Every git step past
# the clone is best-effort: no network is a report line, not a failure.
memory_pass() {
  st=$(memory_store)
  if [ ! -d "$st/.git" ]; then
    if git clone --quiet "$(memory_remote)" "$st" 2>/dev/null; then
      echo "  memory    cloned $st"
    else
      echo "  memory    no store at $st and clone failed — pass skipped"
      echo "            (private repo: needs git access to $(memory_remote))"
      return 0
    fi
  fi
  mkdir -p "$st/memory"
  # Seed the two repo-level files once; never clobber a hand edit.
  [ -e "$st/.gitattributes" ] || echo 'MEMORY.md merge=union' > "$st/.gitattributes"
  [ -e "$st/.gitignore" ] || printf '*.jsonl\n.credentials.json\n' > "$st/.gitignore"
  # A merge left behind by a killed hook would hand the next session a
  # MEMORY.md full of conflict markers. Abort it; doctor reports diverged.
  [ -e "$st/.git/MERGE_HEAD" ] && git -C "$st" merge --abort >/dev/null 2>&1
  git -C "$st" pull --no-rebase --autostash --quiet >/dev/null 2>&1 || true

  total=0; newly=0; imported=0; kept=""
  newnames=$(mktemp)
  while IFS=$'\t' read -r pdir label; do
    [ -n "$pdir" ] || continue
    total=$((total + 1))
    # Names present AFTER the link that were absent BEFORE are the imports.
    before=$(find "$st/memory" -maxdepth 1 -name '*.md' -exec basename {} \; | sort)
    out=$(memory_link "$pdir" "$st/memory")
    case "$out" in
      warn*)     echo "  WARN      ${out#*$'\t'}" ;;
      linked)    newly=$((newly + 1)) ;;
      imported*) n=$(printf '%s' "$out" | cut -f2); k=$(printf '%s' "$out" | cut -f3)
                 imported=$((imported + n)); newly=$((newly + 1))
                 [ -n "$k" ] && kept="$kept $label:{$k}"
                 find "$st/memory" -maxdepth 1 -name '*.md' -exec basename {} \; | sort |
                   comm -13 <(printf '%s\n' "$before") - >> "$newnames" ;;
    esac
  done <<< "$(memory_slug_dirs "$root")"

  memory_render_index "$st/memory"
  count=$(find "$st/memory" -maxdepth 1 -name '*.md' ! -name MEMORY.md | wc -l)
  printf '  memory    %s slugs -> %s/memory  (%s memories, %s newly linked, %s imported)\n' \
    "$total" "$st" "$count" "$newly" "$imported"
  [ -n "$kept" ] && echo "            kept in store, originals beside each link as memory.pre-sync/:$kept"
  if [ -s "$newnames" ]; then
    ov=$(memory_overlaps "$st/memory" "$newnames")
    if [ -n "$ov" ]; then
      echo "            overlap — same topic on both machines? read both, merge by hand if so:"
      printf '%s\n' "$ov"
    fi
  fi
  rm -f "$newnames"

  git -C "$st" add -A >/dev/null 2>&1 || true
  if ! git -C "$st" diff --cached --quiet 2>/dev/null; then
    git -C "$st" commit --quiet -m "memory: import $imported from $(hostname -s 2>/dev/null || echo host)" >/dev/null 2>&1 || true
    # -u every time: the first push into an empty remote has no upstream,
    # and repeating it later is harmless.
    if git -C "$st" push --quiet -u origin HEAD >/dev/null 2>&1; then
      echo "            committed and pushed"
    else
      echo "            committed; push failed (offline?) — doctor will report unpushed"
    fi
  fi

  # The hook script is rewritten every pass (stable path, fresh store
  # path); the settings.json entry is written only on request, because
  # editing a user-global file is consent the user gives once.
  write_memory_hook "$root"
  if [ "$hooks" = true ]; then
    echo '            hooks ship in the nixtastic plugin now — nothing to install; sync registers the plugin'
  fi
}

# The memory pass alone. Sits below the definition it calls; the flag it
# reads was set above, before this point is reached.
if [ "$memory_only" = true ]; then
  memory_pass
  exit 0
fi

# Repos whose direnv files were (re)written, for the footer. A temp file
# rather than a variable: historical (the loop was once a pipeline
# subshell), and still the safer shape if it ever becomes one again.
pending=$(mktemp)
trap 'rm -f "$pending"' EXIT

while IFS=$'\t' read -r dir repo shell; do
  if [ ! -d "$root/$dir/.git" ]; then
    echo "  clone     $dir  <- $repo"
    # --recurse-submodules: firmware ships two (protobufs,
    # meshtestic) and meshtastic-python vendors protobufs the
    # same way, and a plain clone leaves them as empty
    # directories — pio then fails on missing proto sources.
    # Generic, not a firmware special case. The only other path
    # that initializes them is the post-fast-forward re-sync,
    # which never fires for a fresh, up-to-date clone.
    git clone --quiet --recurse-submodules "https://github.com/$repo.git" "$root/$dir"
    # A fresh clone may already carry a tracked .envrc of its
    # own (firmware does), so route through the same check.
    if [ ! -e "$root/$dir/.envrc" ]; then
      write_envrc "$root/$dir/.envrc" "$shell"
    else
      write_envrc "$root/$dir/.envrc-workspace" "$shell"
    fi
    echo "$dir" >> "$pending"
    continue
  fi

  g="git -C $root/$dir"

  # Give the repo its own dev shell, once. Never clobber a file
  # that is already there — except one WE wrote whose shell the
  # table has since renamed (repair_envrc in lib.sh): that one is
  # rewritten, and direnv will want a fresh `allow` for it.
  envrc=""
  if [ ! -e "$root/$dir/.envrc" ]; then
    write_envrc "$root/$dir/.envrc" "$shell"
    envrc="envrc written"
  elif $g ls-files --error-unmatch .envrc >/dev/null 2>&1; then
    # Upstream TRACKS its own .envrc. firmware ships `use nix`,
    # which resolves to UPSTREAM's flake and its bwrap-broken
    # pkgs.platformio. Editing a tracked file would leave the
    # repo permanently dirty — blocking --pull — and could be
    # committed into an org PR, so write the sidecar that the
    # workspace direnvrc prefers and leave theirs alone.
    if [ ! -e "$root/$dir/.envrc-workspace" ]; then
      write_envrc "$root/$dir/.envrc-workspace" "$shell"
      envrc="envrc-workspace written (upstream tracks .envrc)"
    else
      envrc=$(repair_envrc "$root/$dir/.envrc-workspace" "$shell" write_envrc)
    fi
  else
    envrc=$(repair_envrc "$root/$dir/.envrc" "$shell" write_envrc)
  fi
  case "$envrc" in
    WARN*) echo "  WARN      $dir: ${envrc#WARN }"; envrc="" ;;
    ?*) echo "$dir" >> "$pending" ;;
  esac

  # Adopt worktrees this tool did not create — hand-made
  # (`git worktree add`), agent-skill-made, or an agent
  # harness's worktree isolation. Shell selection is NOT the
  # gap it once was: a worktree under the repo inherits the
  # repo's own .envrc from the nearest ancestor (verified:
  # right shell, right MESHTASTIC_WORKSPACE). What still
  # fails silently is (a) a repo that TRACKS its .envrc —
  # firmware's `use nix` wins without the sidecar — (b) the
  # per-directory .mcp.json, without which the MCP tools are
  # simply absent, and (c) a worktree parked outside the
  # repo tree, which has no ancestor to inherit. Outfit all
  # three here, idempotently, never clobbering.
  ensure_excludes "$root/$dir"
  $g worktree list --porcelain | sed -n 's/^worktree //p' | tail -n +2 |
  while read -r wt; do
    [ -d "$wt" ] || continue
    got=""
    # Tracked-ness is checked IN THE WORKTREE: its branch,
    # not the main checkout's, decides what it carries.
    if git -C "$wt" ls-files --error-unmatch .envrc >/dev/null 2>&1; then
      if [ ! -e "$wt/.envrc-workspace" ]; then
        write_worktree_envrc "$wt/.envrc-workspace" "$shell"
        got="envrc-workspace"
      else
        got=$(repair_envrc "$wt/.envrc-workspace" "$shell" write_worktree_envrc)
      fi
    else
      case "$wt/" in
        "$root/$dir/"*) ;; # ancestor .envrc covers it
        *)
          if [ ! -e "$wt/.envrc" ]; then
            write_worktree_envrc "$wt/.envrc" "$shell"
            got="envrc — approve once: direnv allow $wt"
          else
            got=$(repair_envrc "$wt/.envrc" "$shell" write_worktree_envrc)
            [ -n "$got" ] && got="$got — approve again: direnv allow $wt"
          fi
          ;;
      esac
    fi
    case "$got" in
      WARN*) echo "  WARN      $dir/${wt##*/}: ${got#WARN }"; got="" ;;
    esac
    # Upstream may TRACK .mcp.json (android, firmware and
    # meshtastic-mcp do — android's registers context7 for
    # the team). Overwriting would dirty the worktree and
    # stomp those registrations, so a tracked file wins and
    # ours is never written beside it. An UNtracked one is
    # ours: regenerate it every pass, exactly like the root
    # copy, so a flake update cannot leave stale store
    # paths — but only report when it was missing outright.
    if ! git -C "$wt" ls-files --error-unmatch .mcp.json >/dev/null 2>&1; then
      fresh=false
      [ -f "$wt/.mcp.json" ] || fresh=true
      if write_mcp_json "$wt" "$root" && [ "$fresh" = true ]; then
        got="${got:+$got, }mcp.json"
      fi
    fi
    # if/fi, not `[ ] &&`: as the body's last command its
    # failure would become the pipeline's exit status.
    if [ -n "$got" ]; then
      printf '  adopted   %-24s %s\n' "$dir/${wt##*/}" "$got"
    fi
  done

  # A --single-branch clone narrows remote.origin.fetch to a
  # single ref, so `git fetch` can NEVER see any other
  # branch and drift on them is invisible. Detect it, and
  # widen under --pull (this is just the normal clone
  # default; nothing is discarded).
  narrow=false
  case "$($g config --get-all remote.origin.fetch | tr '\n' ' ')" in
    *"refs/heads/*"*) ;;
    *) narrow=true ;;
  esac
  if [ "$narrow" = true ] && [ "$pull" = true ]; then
    $g config --replace-all remote.origin.fetch \
      '+refs/heads/*:refs/remotes/origin/*'
    narrow=false
  fi

  # Fetch is always safe — it only writes remote-tracking refs.
  $g fetch --quiet --prune --tags origin 2>/dev/null || true

  # --main moves to the repo's DEFAULT branch. NOT hardcoded
  # to "main": meshtastic-mcp's default is master. Resolved
  # from origin/HEAD, repairing it via `remote set-head` if
  # the clone never recorded one.
  switched=""
  if [ "$main" = true ]; then
    if ! ref=$($g symbolic-ref --quiet refs/remotes/origin/HEAD 2>/dev/null); then
      $g remote set-head origin --auto >/dev/null 2>&1 || true
      ref=$($g symbolic-ref --quiet refs/remotes/origin/HEAD 2>/dev/null || true)
    fi
    def="${ref#refs/remotes/origin/}"
    cur=$($g rev-parse --abbrev-ref HEAD)
    if [ -n "$def" ] && [ "$def" != "$cur" ]; then
      # Switching a dirty tree would drag the modifications
      # onto the default branch. Leave it exactly where it is.
      if [ "$($g status --porcelain --untracked-files=no | wc -l)" -gt 0 ]; then
        switched="STAYED on $cur (tree dirty)"
      elif $g rev-parse --verify --quiet "refs/heads/$def" >/dev/null 2>&1; then
        $g checkout --quiet "$def" && switched="$cur -> $def"
      else
        $g checkout --quiet -b "$def" --track "origin/$def" \
          && switched="$cur -> $def (new local branch)"
      fi
    fi
  fi

  branch=$($g rev-parse --abbrev-ref HEAD)
  # Only TRACKED modifications can block a fast-forward.
  # Untracked files cannot (git merge --ff-only happily
  # ignores them), so counting them as "dirty" would
  # needlessly skip repos — e.g. meshtastic-mcp, held back
  # by nothing but an untracked .remember/ directory.
  dirty=$($g status --porcelain --untracked-files=no | wc -l)
  untracked=$($g ls-files --others --exclude-standard | wc -l)

  # Missing tracking config does NOT mean missing remote
  # branch. Checking out a fetched ref, or pushing without
  # -u, leaves a branch with no upstream that nonetheless
  # exists on origin. Treating that as "nothing to compare"
  # silently hides real drift, so fall back to
  # origin/<branch> before giving up.
  tracked=true
  if ! upstream=$($g rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null); then
    if $g rev-parse --verify --quiet "refs/remotes/origin/$branch" >/dev/null 2>&1; then
      upstream="origin/$branch"
      tracked=false
    else
      if [ "$narrow" = true ]; then
        why="not fetched (single-branch clone; --pull widens it)"
      else
        why="not on origin"
      fi
      printf '  local     %-24s %-30s %-10s %s\n' \
        "$dir" "$branch" ".#$shell" "$why${envrc:+, $envrc}"
      continue
    fi
  fi

  # left = commits upstream has that we lack (behind)
  # right = commits we have that upstream lacks (ahead)
  counts=$($g rev-list --left-right --count "$upstream...HEAD")
  behind=$(echo "$counts" | cut -f1)
  ahead=$(echo "$counts" | cut -f2)

  # flags describe the working tree; drift describes the
  # branch. Keep them separate so a drift message can never
  # swallow the fact that the tree is dirty.
  flags=""
  [ -n "$switched" ] && flags="$switched"
  [ "$narrow" = true ] && flags="${flags}${flags:+, }single-branch clone"
  [ "$tracked" = false ] && flags="${flags}${flags:+, }no tracking"
  [ "$dirty" -gt 0 ] && flags="${flags}${flags:+, }$dirty dirty"
  [ "$untracked" -gt 0 ] && flags="${flags}${flags:+, }$untracked untracked"
  [ -n "$envrc" ] && flags="${flags}${flags:+, }$envrc"

  if [ "$behind" -eq 0 ] && [ "$ahead" -eq 0 ]; then
    status="current"; drift=""
  elif [ "$ahead" -gt 0 ] && [ "$behind" -gt 0 ]; then
    status="DIVERGED"; drift="+$ahead/-$behind"
  elif [ "$ahead" -gt 0 ]; then
    status="ahead"; drift="+$ahead"
  elif [ "$dirty" -gt 0 ]; then
    status="BEHIND"; drift="-$behind skipped, tree dirty"
  elif [ "$pull" = true ]; then
    # Repair tracking config while we are here; harmless and
    # reversible with `git branch --unset-upstream`.
    [ "$tracked" = false ] && \
      $g branch --quiet --set-upstream-to="$upstream" "$branch" >/dev/null 2>&1
    if $g merge --ff-only --quiet "$upstream" 2>/dev/null; then
      status="PULLED"; drift="-$behind fast-forwarded"
      # A fast-forward can move recorded submodule pointers.
      # Without re-syncing, the tree reads dirty again the
      # instant the pull finishes — firmware/protobufs does
      # this every time upstream bumps the proto pointer.
      if [ -f "$root/$dir/.gitmodules" ]; then
        $g submodule update --init --recursive --quiet 2>/dev/null || true
        drift="$drift +submodules"
      fi
    else
      status="FAILED"; drift="-$behind ff refused"
    fi
  else
    status="behind"; drift="-$behind (run with --pull)"
  fi

  printf '  %-9s %-24s %-30s %-10s %s\n' \
    "$status" "$dir" "$branch" ".#$shell" \
    "$drift${drift:+${flags:+  }}$flags"
done < "$NIXTASTIC_REPOS_TSV"

echo ""

# --- aggregate per-repo subagents into the workspace root -------------
# Rationale (and why copies, not symlinks) lives with agent_pairs in lib.sh.
agents_dir="$root/.claude/agents"
expected=$(mktemp)
want=$(mktemp)
trap 'rm -f "$pending" "$expected" "$want"' EXIT
while IFS=$'\t' read -r dir _ _; do
  agent_pairs "$dir" "$root" >> "$expected"
done < "$NIXTASTIC_REPOS_TSV"

agents_written=0
agents_dropped=0
cut -f2 "$expected" > "$want"

if [ -s "$expected" ]; then
  mkdir -p "$agents_dir"
  while IFS=$'\t' read -r src dest; do
    # cmp so an unchanged agent is not rewritten every sync — the mtime
    # churn would make "is this stale?" unanswerable by inspection.
    if ! cmp -s "$src" "$agents_dir/$dest"; then
      cp "$src" "$agents_dir/$dest"
      agents_written=$((agents_written + 1))
    fi
  done < "$expected"
fi

# Deliberately OUTSIDE the guard above: when the last agent upstream is
# deleted, $expected is empty, and a drop pass nested in that guard would
# never run — the orphan copy would answer forever. Worse than absent,
# and invisible.
if [ -d "$agents_dir" ]; then
  for f in "$agents_dir"/*.md; do
    [ -f "$f" ] || continue
    if ! grep -qxF "${f##*/}" "$want"; then
      rm -f "$f"
      agents_dropped=$((agents_dropped + 1))
    fi
  done
fi

if [ -s "$expected" ]; then
  n=$(wc -l < "$expected")
  printf '  .claude/agents  %s subagent(s) from %s — usable from the root\n' \
    "$n" "$(cut -f2 "$expected" | sed 's/--.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')"
  [ "$agents_written" -gt 0 ] && printf '      %s copied (source changed)\n' "$agents_written"

  # Two repos shipping the same frontmatter name would resolve by
  # filesystem read order — undefined, and silently the wrong agent. The
  # prefixed filenames cannot prevent this; only saying so can.
  dupes=$(while IFS=$'\t' read -r src _; do agent_name_of "$src"; done < "$expected" | sort | uniq -d)
  if [ -n "$dupes" ]; then
    echo "  WARN  duplicate subagent name(s) across repos — resolution is undefined:"
    printf '        %s\n' "$dupes"
  fi
fi

# Reported outside the block above so the last agent's removal is still
# announced — a copy vanishing silently is the same invisibility problem
# in the other direction.
[ "$agents_dropped" -gt 0 ] && printf '  .claude/agents  %s dropped (source gone)\n' "$agents_dropped"

# The --add-dir launcher stays as an edge case (loads a repo's CLAUDE.md
# too); the plugin's forwarders are the everyday door to repo skills.
write_claude_launcher "$root"

memory_pass
plugin_pass "$root"

if write_mcp_json "$root" "$root"; then
  echo "  .mcp.json written — meshtastic-mcp server for this workspace"
  # A project-scope server is approved once per machine, the
  # same consent model as direnv. Say so rather than letting
  # it look broken on first use.
  echo "      approve once:  claude  (then /mcp)"
  # The stable launcher a USER-scope registration points at; rewritten
  # with fresh store paths every run so `nix flake update` cannot strand
  # that registration. Rationale with write_mcp_launcher in lib.sh.
  write_mcp_launcher "$root"
  if ! jq -e '.mcpServers.meshtastic' "$HOME/.claude.json" >/dev/null 2>&1; then
    echo "  no user-scope registration — the tools are absent in android/,"
    echo "  firmware/ and their worktrees (upstream's tracked .mcp.json wins"
    echo "  there) until you run, once ever:"
    echo "      claude mcp add --scope user meshtastic -- $root/bin/meshtastic-mcp-launch"
  fi
  echo ""
fi
if [ -s "$pending" ]; then
  # direnv deliberately requires explicit consent per .envrc; we
  # write the file, you approve it. Never automated.
  echo "  direnv files written — approve each once:"
  while read -r d; do
    echo "      direnv allow $root/$d"
  done < "$pending"
  echo ""
fi
if [ "$pull" = true ]; then
  echo "  fast-forwarded where safe; dirty/diverged repos untouched"
else
  echo "  read-only. re-run to act:"
  echo "      nix run .#sync -- --pull    fast-forward current branches"
  echo "      nix run .#sync -- --main    switch to default branch, then pull"
fi
echo "  enter a shell with:  nix develop .#<shell>"

